### ISSUE TITLE
Mod doesn't work and breaks Zen's popups

### ISSUE THREAD

**Issue by cringifyq** [Dinno-DEV/zen-tidy-popup#1]
![Image](https://github.com/user-attachments/assets/08cbd805-7fec-4b23-bf64-9314c1679694)

Even during a fresh install the mod still refuses to work, When using custom colors the colors briefly appear then disappear, I think the mod might be overlapping with Zen's UI

**Comment by sannidhyaroy** [comment]
+1

**Comment by CosmoCreeper** [comment]
+1

I'm not a main user of this mod (at least not yet) but I love fixing mods like this. I'll create a pull request once I get it working again!

**Comment by CosmoCreeper** [comment]
Fixed in #2! Please upvote my pull request if it works for you!

**Comment by bsrmdn** [comment]
I still have this issue, even after uninstall this mod, the bug seems still remain

**Comment by CosmoCreeper** [comment]
Did you update to the github version instead of the theme store version.

**Comment by bsrmdn** [comment]
i have update it to the github version, but the icon padding still not work

![Image](https://github.com/user-attachments/assets/dbb92f36-f6ca-481e-b215-57d27d6260a6)

**Comment by bsrmdn** [comment]
it's fixed after the browser update to 1.12.1b, the plugin icon looks offset though

![Image](https://github.com/user-attachments/assets/fc1715bb-12b8-4e85-8e7e-26e7527bcc9c)

**Comment by CosmoCreeper** [comment]
Ahhh. You know what, I probably coded it to work on newer versions of zen. I'll look into the extension icon soon. (It just seems like i got a lot on my hands rn)

**Comment by painelle** [comment]
+1 it is broken as of right now 05/24/2025

**Comment by progzone122** [comment]
+1, broken 28.05.2025
